branch-defaults:
  dev:
    environment: null
    group_suffix: null
  master:
    environment: trackmywaterchange
deploy:
  artifact: target/trackmywaterchange-0.0.1-SNAPSHOT.jar
  
global:
  application_name: trackmywaterchange
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Java 8
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
